apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: helloworlds.examples.codesink.io
spec:
  group: examples.codesink.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Cluster
  subresources:
    status: {}
  names:
    plural: helloworlds
    singular: helloworld
    kind: HelloWorld
