---
- name: /etc/systemd/system/etcd-member.service.d
  file:
    path: /etc/systemd/system/etcd-member.service.d
    state: directory

- name: 20-etcd-member.conf
  copy:
    dest: /etc/systemd/system/etcd-member.service.d/20-etcd-member.conf
    content: |
      [Unit]
      Requires=coreos-metadata.service
      After=coreos-metadata.service

      [Service]
      EnvironmentFile=/run/metadata/coreos
      Environment=RKT_RUN_ARGS="--volume pki,kind=host,source=/etc/kubernetes/pki/etcd/,readOnly=true --mount volume=pki,target=/etc/kubernetes/pki/etcd/" 
      ExecStart=
      ExecStart=/usr/lib/coreos/etcd-wrapper $ETCD_OPTS \
        --listen-peer-urls="https://0.0.0.0:2380" \
        --listen-client-urls="https://0.0.0.0:2379" \
        --initial-advertise-peer-urls="https://${COREOS_DIGITALOCEAN_IPV4_PUBLIC_0}:2380" \
        --advertise-client-urls="https://{{ ansible_local['node']['general']['etcd_hostname'] }}:2379" \
        --discovery="{{ ansible_local['node']['general']['etcd_discovery_token'] }}" \
        --trusted-ca-file="/etc/kubernetes/pki/etcd/ca.crt" \
        --cert-file="/etc/kubernetes/pki/etcd/server.crt" \
        --key-file="/etc/kubernetes/pki/etcd/server.key" \
        --client-cert-auth=true \
        --peer-client-cert-auth=true \
        --peer-auto-tls=true

- name: start etcd-member
  systemd:
    state: started
    daemon_reload: yes
    enabled: yes
    masked: no
    name: etcd-member
    no_block: yes
